### ISSUE TITLE
No color written

### ISSUE THREAD

**Issue by vstrg** [ItsBranK/TradeLogger#2]
Hey, this octane is white but it only says octane, is it possible to write it as Titanium White Octane?

```
[
	{
		"LocalPlayer": "Epic|x|0",
		"LocalProducts": ["Octane"],
		"LocalInstances": ["0-33447691118"],
		"LocalCurrencyId": -1,
		"LocalCurrencyAmount": 0,
		"RemotePlayer": "x",
		"RemoteProducts": [""],
		"RemoteInstances": [""],
		"RemoteCurrencyId": 13,
		"RemoteCurrencyAmount": 3800,
		"TradeGuid": "B150D16D-4DAD3B03-D2880FBD-0398425F",
		"TradeGuidFormat": "EGuidFormats::UniqueObjectGuid",
		"TradeStartEpoch": "1694197475",
		"TradeEndEpoch": "1694197523"
	}
]
```

**Comment by vstrg** [comment]
😢

**Comment by ItsBrank** [comment]
I don't make BM plugins anymore, so if you want this added you can do it yourself and submit a PR here. Then I'd push the update to bakkesplugins. Seeing as Epic Games is removing trade anyway next month, might be a little too late.

**Comment by vstrg** [comment]
> I don't make BM plugins anymore, so if you want this added you can do it yourself and submit a PR here. Then I'd push the update to bakkesplugins. Seeing as Epic Games is removing trade anyway next month, might be a little too late.

as you said, Epic Games is removing trade, it doesn't matter anymore. thanks for everything
